<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>DC_BotWorker</RootNamespace>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="NetCord" Version="1.0.0-alpha.453" />
    </ItemGroup>

</Project>
